import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import tseslint from "typescript-eslint";
import jsxA11y from "eslint-plugin-jsx-a11y";
import playwright from "eslint-plugin-playwright";
import vitest from "@vitest/eslint-plugin";
import eslintConfigPrettier from "eslint-config-prettier";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // Type-aware TypeScript linting. Scoped to **/*.{ts,tsx} via `extends` so
  // the type-checked parser/rules never spread onto plain .mjs scripts that
  // aren't in tsconfig.json's `include` (they'd fail to parse otherwise).
  {
    files: ["**/*.{ts,tsx}"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Already 'error' in recommendedTypeChecked — kept explicit because
      // these two are the regression guard for unawaited Server Action /
      // Supabase calls; a future typescript-eslint default change should not
      // silently soften them.
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
    },
  },

  // Defense-in-depth: even though the block above is scoped away from
  // **/*.mjs, explicitly disable the type-checked overlay for plain Node
  // scripts (eslint.config.mjs, postcss.config.mjs, tests/e2e/*.mjs) so
  // adding a stray `files`-less type-checked rule later can't reintroduce
  // the projectService parse failure on files tsconfig.json doesn't cover.
  {
    files: ["**/*.mjs"],
    extends: [tseslint.configs.disableTypeChecked],
  },

  // jsx-a11y: eslint-config-next's core-web-vitals block already registers
  // the `jsx-a11y` plugin with only 6 rules enabled. Merge in the plugin's
  // full `recommended` RULE MAP only — re-declaring the `jsx-a11y` plugin
  // key here would throw (duplicate plugin identity in flat config).
  {
    rules: {
      ...jsxA11y.flatConfigs.recommended.rules,
    },
  },

  // Import hygiene. `eslint-plugin-import` is already registered by
  // core-web-vitals (with only `no-anonymous-default-export` on); add
  // ordering on top, same non-re-declaration reasoning as jsx-a11y above.
  {
    rules: {
      "import/order": [
        "error",
        {
          "newlines-between": "always",
        },
      ],
    },
  },

  // Playwright spec files only — not the plain .mjs helper scripts, which
  // aren't specs (they don't import @playwright/test's test/expect).
  {
    files: ["tests/e2e/**/*.spec.ts"],
    extends: [playwright.configs["flat/recommended"]],
  },

  // Vitest unit test files only. Scope tracks `vitest.config.ts`'s two
  // projects: `lib/**` + `app/**` run under `node`, `hooks/**` under `jsdom`.
  {
    files: ["lib/**/*.test.ts", "hooks/**/*.test.ts", "app/**/*.test.ts"],
    extends: [vitest.configs.recommended],
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vitest coverage output (auto-generated)
    "coverage/**",
    // Tool-owned trees — mirrors `.prettierignore`. These hold machine-generated
    // artifacts (rebuild-spec drafts, promoted spec layer, plan scripts) that are
    // regenerated by tooling, so linting them would fail the build on content no
    // human authored. Verified 2026-09-05: without these, `eslint .` really did
    // reach a tracked `.mjs` under `plans/` — clean that day, but a latent trap.
    "plans/**",
    "docs/**",
    ".claude/**",
    // Playwright/test output
    "test-results/**",
    "playwright-report/**",
    // Storybook build output (generated).
    "storybook-static/**",
    // MSW's service worker, generated verbatim by `msw init` and version-
    // matched to the installed msw. `eslint` runs bare here (no path arg), so
    // it does sweep `public/` — without this line the first `msw init` turns
    // `pnpm lint` red on a file no human wrote and no human may edit.
    "public/mockServiceWorker.js",
  ]),

  // Prettier integration: disables ESLint's own stylistic/formatting rules
  // so it never fights Prettier's output. This config only turns rules OFF —
  // it adds none — so it must be spread LAST to win over every block above.
  eslintConfigPrettier,
]);

export default eslintConfig;
