import { BrowserContext } from "@playwright/test";
import { createServerClient } from "@supabase/ssr";

/**
 * Sign in or sign up a test user via GoTrace REST API.
 * Handles idempotency: if user exists, falls back to password grant.
 * @param metadata Optional metadata to include in user data (e.g., { full_name: "..." })
 */
export async function createTestSession(
  supabaseUrl: string,
  publishableKey: string,
  email: string,
  password: string,
  metadata: Record<string, unknown> = {},
): Promise<{ access_token: string; refresh_token: string; user_id: string }> {
  // Try to sign up first
  const signupResponse = await fetch(`${supabaseUrl}/auth/v1/signup`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      apikey: publishableKey,
    },
    body: JSON.stringify({
      email,
      password,
      // Top-level `data`, NOT `options.data`. This calls the GoTrue REST
      // endpoint directly; `options` is a supabase-js concept that the SDK
      // unwraps into `data` before it ever hits the wire. Sending
      // `options.data` here is silently discarded, leaving
      // `raw_user_meta_data` empty — migration 0002's trigger then writes
      // `full_name` NULL, and its `ON CONFLICT (id) DO NOTHING` means no
      // later signup can ever repair that row.
      data: metadata,
    }),
  });

  interface SessionResponse {
    access_token?: string;
    refresh_token?: string;
    user?: { id: string };
    [key: string]: unknown;
  }
  let sessionData: SessionResponse = {};

  if (signupResponse.status === 422) {
    // User already exists, use password grant
    const tokenResponse = await fetch(
      `${supabaseUrl}/auth/v1/token?grant_type=password`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          apikey: publishableKey,
        },
        body: JSON.stringify({
          email,
          password,
        }),
      },
    );
    sessionData = (await tokenResponse.json()) as SessionResponse;
  } else if (signupResponse.ok) {
    sessionData = (await signupResponse.json()) as SessionResponse;
  } else {
    throw new Error(
      `Failed to create test session: ${signupResponse.status} ${signupResponse.statusText}`,
    );
  }

  if (!sessionData.access_token || !sessionData.user) {
    throw new Error(
      `No valid session in response from GoTrue: ${JSON.stringify(sessionData)}`,
    );
  }

  return {
    access_token: sessionData.access_token || "",
    refresh_token: sessionData.refresh_token || "",
    user_id: sessionData.user?.id || "",
  };
}

/**
 * Generate Supabase session cookies using @supabase/ssr library.
 * This ensures cookies are in the exact format that the library expects.
 */
export async function generateSupabaseCookies(
  supabaseUrl: string,
  publishableKey: string,
  accessToken: string,
  refreshToken: string,
): Promise<Array<{ name: string; value: string }>> {
  const captured: Array<{ name: string; value: string }> = [];

  // Use @supabase/ssr to generate the cookies in the correct format
  const sb = createServerClient(supabaseUrl, publishableKey, {
    cookies: {
      getAll: () => [],
      setAll: (cookiesToSet) => {
        cookiesToSet.forEach((c) => {
          captured.push({ name: c.name, value: c.value });
        });
      },
    },
  });

  // Set the session — this will trigger setAll with the properly formatted cookies
  const { error } = await sb.auth.setSession({
    access_token: accessToken,
    refresh_token: refreshToken,
  });

  if (error) {
    throw new Error(`Failed to set session: ${error.message}`);
  }

  return captured;
}

/**
 * Inject Supabase session cookies into the browser context.
 * Uses cookies generated by @supabase/ssr, ensuring correct format.
 */
export async function injectSupabaseSession(
  context: BrowserContext,
  cookies: Array<{ name: string; value: string }>,
): Promise<void> {
  // Set cookies on localhost:3000 (the app origin)
  await context.addCookies(
    cookies.map((c) => ({
      name: c.name,
      value: c.value,
      domain: "localhost",
      path: "/",
      httpOnly: false,
      secure: false,
      sameSite: "Lax" as const,
    })),
  );
}
